### ISSUE TITLE
Autenticación con Google !! (link al issue)

### ISSUE THREAD

**Issue by amatriaindavid7** [garcesote/elCARtua#4]

**Comment by garcesote** [comment]
Dejo por aquí la primera fase de autenticación con google la cual permite iniciar sesión con las credenciales de google. Es necesario correr el código con expo dev y no con expo go. NO esta desarrollado la gestión de usuarios de la aplicación en la db.

**Comment by garcesote** [comment]
Ya desarrollada la creación de usuarios en la base de datos con la autenticación de google, usuarios se guardan si no tienen ya una cuenta con su google id. La información de usuario se guarda en asyncStorage para tener el almacenamiento persistente.
