### ISSUE TITLE
Creación de grupos (db) !! (link al issue)

### ISSUE THREAD

**Issue by amatriaindavid7** [garcesote/elCARtua#5]

**Comment by garcesote** [comment]
La idea es empezar creando un grupo por usuario y luego si el usuario no tiene grupo, poder unirse al grupo con el id único que tenga.

**Comment by garcesote** [comment]
App lista para crear, unirse y borrar los grupos. Se ha creado la app de tal forma que puedas crear un grupo y añadir varios vehículos o la otra opción es que te unas a un grupo mediante un código único para cada grupo. Además el usuario podrá borrar el grupo y todos los usuarios que lo conformen saldrán de este.
