### ISSUE TITLE
Integración de cámara para las fotos y mas funcionalidades (link al issue)

### ISSUE THREAD

**Issue by amatriaindavid7** [garcesote/elCARtua#7]

**Comment by garcesote** [comment]
Se ha utilizado la librería React Native Image picker. El usuario puede acceder a una pantalla donde puede sacar la foto y posteriormente se muestra por pantalla. Falta subirla y descargarla en caso de que haya para mostrar la imagen del coche.

**Comment by garcesote** [comment]
Se ha conseguido subir fotos y mostrarlas pulsando en el icono de la cámara del contenedor de cada vehículo. Para ello se ha empleado el método usado por firebase react native de tareas para subir el archivo y el método de solicitar la url para el tema de descargas.
